### ISSUE TITLE
Using abs(int) instead of fabs(double) ?

### ISSUE THREAD

**Issue by mkotlyar** [giaf/hpmpc#14]
`Clang` issues multiple warnings like this:

```
warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
```

Was it an intent to use the integer version of `abs()` or is it a mistake?

 [clang_output.txt](https://github.com/giaf/hpmpc/files/355597/clang_output.txt)

**Comment by giaf** [comment]
fixed
