### ISSUE TITLE
Issue compiling test_problems

### ISSUE THREAD

**Issue by ggleizer** [giaf/hpmpc#23]
Hello,

First of all, thanks for the amazing work and for making it open source. 

I'm trying to compile the whole package using 'make' but compilation is failing when entering test_problems, particularly at 'test_d_ip_hard_libstr.c". The log is below. Thanks in advance.

`[predix@localhost test_problems]$ make
gcc -O2 -fPIC  -m64 -mavx -DTARGET_X64_AVX     -c -o test_d_ip_hard_libstr.o test_d_ip_hard_libstr.c
test_d_ip_hard_libstr.c: In function ‘main’:
test_d_ip_hard_libstr.c:289: error: storage size of ‘sA’ isn’t known
test_d_ip_hard_libstr.c:294: error: storage size of ‘sx0’ isn’t known
test_d_ip_hard_libstr.c:299: error: storage size of ‘sb0’ isn’t known
test_d_ip_hard_libstr.c:308: error: storage size of ‘sBAbt0’ isn’t known
test_d_ip_hard_libstr.c:315: error: storage size of ‘sBAbt1’ isn’t known
test_d_ip_hard_libstr.c:316: error: storage size of ‘sb1’ isn’t known
test_d_ip_hard_libstr.c:346: error: storage size of ‘sRSQrq0’ isn’t known
test_d_ip_hard_libstr.c:347: error: storage size of ‘srq0’ isn’t known
test_d_ip_hard_libstr.c:360: error: storage size of ‘sRSQrq1’ isn’t known
test_d_ip_hard_libstr.c:361: error: storage size of ‘srq1’ isn’t known
test_d_ip_hard_libstr.c:377: error: storage size of ‘sRSQrqN’ isn’t known
test_d_ip_hard_libstr.c:378: error: storage size of ‘srqN’ isn’t known
test_d_ip_hard_libstr.c:492: error: storage size of ‘sDCt0’ isn’t known
test_d_ip_hard_libstr.c:496: error: storage size of ‘sd0’ isn’t known
test_d_ip_hard_libstr.c:501: error: storage size of ‘sDCt1’ isn’t known
test_d_ip_hard_libstr.c:505: error: storage size of ‘sd1’ isn’t known
test_d_ip_hard_libstr.c:510: error: storage size of ‘sDCtN’ isn’t known
test_d_ip_hard_libstr.c:514: error: storage size of ‘sdN’ isn’t known
test_d_ip_hard_libstr.c:523: error: array type has incomplete element type
test_d_ip_hard_libstr.c:524: error: array type has incomplete element type
test_d_ip_hard_libstr.c:525: error: array type has incomplete element type
test_d_ip_hard_libstr.c:526: error: array type has incomplete element type
test_d_ip_hard_libstr.c:528: error: array type has incomplete element type
test_d_ip_hard_libstr.c:529: error: array type has incomplete element type
test_d_ip_hard_libstr.c:530: error: array type has incomplete element type
test_d_ip_hard_libstr.c:531: error: array type has incomplete element type
test_d_ip_hard_libstr.c:614: error: array type has incomplete element type
test_d_ip_hard_libstr.c:615: error: array type has incomplete element type
test_d_ip_hard_libstr.c:616: error: array type has incomplete element type
test_d_ip_hard_libstr.c:617: error: array type has incomplete element type
test_d_ip_hard_libstr.c:618: error: array type has incomplete element type
test_d_ip_hard_libstr.c:619: error: array type has incomplete element type
test_d_ip_hard_libstr.c:673: error: array type has incomplete element type
test_d_ip_hard_libstr.c:674: error: array type has incomplete element type
test_d_ip_hard_libstr.c:675: error: array type has incomplete element type
test_d_ip_hard_libstr.c:676: error: array type has incomplete element type
make: *** [test_d_ip_hard_libstr.o] Error 1
`

**Comment by giaf** [comment]
Hey,

thanks for the interest in the project :)

BLASFEO [(https://github.com/giaf/blasfeo)] is a new software project I started recently, with the aim of improving the linear algebra I originally developed for HPMPC. At the moment there are two entirely independent software stacks in HPMPC, one using BLASFEO and one using the old linear algebra within HPMPC. For sure new developments will be done only in the software stack using BLASFEO, so if there is no reason to not use it, I would suggest you to switch to that. Maybe at some point I will remove the old software stack, I still have to think about.

Two entirely software stacks means that also the test problems are different ;) All test problems ending with _libstr are BLASFEO only, and the other ones are without BLASFEO only. 

Sorry for not clarifying it somewhere. I will make the test problems throw an error if used with the wrong linear algebra.

**Comment by giaf** [comment]
Ah, you can choose the test problem you want to compile and run by commenting out the relative line in test_problems/Makefile.

**Comment by ggleizer** [comment]
Ok, thank you!

Yeah, I have no reason not to use BLASFEO so I'm going to download it and set the flag back to 1 and clone it. Thanks a lot for the quick response!

**Comment by ggleizer** [comment]
Ok, now I have BLASFEO and HPMPC static library compiled using it. I tried compiling test_problems with it (the hard_libstr case) and it failed similarly to the other one. The one without libstr works. Please find the log below:
`[ggleizer@localhost test_problems]$ make
gcc -O2 -fPIC  -m64 -mavx -DTARGET_X64_AVX     -c -o tools.o tools.c
gcc -O2 -fPIC  -m64 -mavx -DTARGET_X64_AVX     -c -o test_d_ip_hard_libstr.o test_d_ip_hard_libstr.c
test_d_ip_hard_libstr.c: In function ‘main’:
test_d_ip_hard_libstr.c:289:18: error: storage size of ‘sA’ isn’t known
  struct d_strmat sA;
                  ^
test_d_ip_hard_libstr.c:294:18: error: storage size of ‘sx0’ isn’t known
  struct d_strvec sx0;
                  ^
test_d_ip_hard_libstr.c:299:18: error: storage size of ‘sb0’ isn’t known
  struct d_strvec sb0;
                  ^
test_d_ip_hard_libstr.c:308:18: error: storage size of ‘sBAbt0’ isn’t known
  struct d_strmat sBAbt0;
                  ^
test_d_ip_hard_libstr.c:315:18: error: storage size of ‘sBAbt1’ isn’t known
  struct d_strmat sBAbt1;
                  ^
test_d_ip_hard_libstr.c:316:18: error: storage size of ‘sb1’ isn’t known
  struct d_strvec sb1;
                  ^
test_d_ip_hard_libstr.c:346:18: error: storage size of ‘sRSQrq0’ isn’t known
  struct d_strmat sRSQrq0;
                  ^
test_d_ip_hard_libstr.c:347:18: error: storage size of ‘srq0’ isn’t known
  struct d_strvec srq0;
                  ^
test_d_ip_hard_libstr.c:360:18: error: storage size of ‘sRSQrq1’ isn’t known
  struct d_strmat sRSQrq1;
                  ^
test_d_ip_hard_libstr.c:361:18: error: storage size of ‘srq1’ isn’t known
  struct d_strvec srq1;
                  ^
test_d_ip_hard_libstr.c:377:18: error: storage size of ‘sRSQrqN’ isn’t known
  struct d_strmat sRSQrqN;
                  ^
test_d_ip_hard_libstr.c:378:18: error: storage size of ‘srqN’ isn’t known
  struct d_strvec srqN;
                  ^
test_d_ip_hard_libstr.c:492:18: error: storage size of ‘sDCt0’ isn’t known
  struct d_strmat sDCt0;
                  ^
test_d_ip_hard_libstr.c:496:18: error: storage size of ‘sd0’ isn’t known
  struct d_strvec sd0;
                  ^
test_d_ip_hard_libstr.c:501:18: error: storage size of ‘sDCt1’ isn’t known
  struct d_strmat sDCt1;
                  ^
test_d_ip_hard_libstr.c:505:18: error: storage size of ‘sd1’ isn’t known
  struct d_strvec sd1;
                  ^
test_d_ip_hard_libstr.c:510:18: error: storage size of ‘sDCtN’ isn’t known
  struct d_strmat sDCtN;
                  ^
test_d_ip_hard_libstr.c:514:18: error: storage size of ‘sdN’ isn’t known
  struct d_strvec sdN;
                  ^
test_d_ip_hard_libstr.c:523:18: error: array type has incomplete element type
  struct d_strmat hsBAbt[N];
                  ^
test_d_ip_hard_libstr.c:524:18: error: array type has incomplete element type
  struct d_strmat hsRSQrq[N+1];
                  ^
test_d_ip_hard_libstr.c:525:18: error: array type has incomplete element type
  struct d_strmat hsDCt[N+1];
                  ^
test_d_ip_hard_libstr.c:526:18: error: array type has incomplete element type
  struct d_strvec hsd[N+1];
                  ^
test_d_ip_hard_libstr.c:528:18: error: array type has incomplete element type
  struct d_strvec hsux[N+1];
                  ^
test_d_ip_hard_libstr.c:529:18: error: array type has incomplete element type
  struct d_strvec hspi[N+1];
                  ^
test_d_ip_hard_libstr.c:530:18: error: array type has incomplete element type
  struct d_strvec hslam[N+1];
                  ^
test_d_ip_hard_libstr.c:531:18: error: array type has incomplete element type
  struct d_strvec hst[N+1];
                  ^
test_d_ip_hard_libstr.c:614:18: error: array type has incomplete element type
  struct d_strvec hsb[N];
                  ^
test_d_ip_hard_libstr.c:615:18: error: array type has incomplete element type
  struct d_strvec hsrq[N+1];
                  ^
test_d_ip_hard_libstr.c:616:18: error: array type has incomplete element type
  struct d_strvec hsrrq[N+1];
                  ^
test_d_ip_hard_libstr.c:617:18: error: array type has incomplete element type
  struct d_strvec hsrb[N];
                  ^
test_d_ip_hard_libstr.c:618:18: error: array type has incomplete element type
  struct d_strvec hsrd[N+1];
                  ^
test_d_ip_hard_libstr.c:619:18: error: array type has incomplete element type
  struct d_strvec hsrm[N+1];
                  ^
test_d_ip_hard_libstr.c:673:18: error: array type has incomplete element type
  struct d_strvec hsux2[N+1];
                  ^
test_d_ip_hard_libstr.c:674:18: error: array type has incomplete element type
  struct d_strvec hspi2[N+1];
                  ^
test_d_ip_hard_libstr.c:675:18: error: array type has incomplete element type
  struct d_strvec hslam2[N+1];
                  ^
test_d_ip_hard_libstr.c:676:18: error: array type has incomplete element type
  struct d_strvec hst2[N+1];
                  ^
make: *** [test_d_ip_hard_libstr.o] Error 1
`

**Comment by giaf** [comment]
Sorry yesterday evening I forgot to push BLASFEO. Just pull it now and it should work.

I also added a /lib folder in BLASFEO, thanks to point it out!

**Comment by ggleizer** [comment]
It compiles now! Thanks a lot!!
