### ISSUE TITLE
K_MAX ignored in test_d_ip_hard_libstr.c

### ISSUE THREAD

**Issue by ggleizer** [giaf/hpmpc#24]
Hi,

I noticed that the value K_MAX we set in test_param.h is not being used in the test_d_ip_hard_libstr.c file. Although it is initially printed as if it were, in line 612 there is a hard coded 10:
`	int k_max = 10;`
This is a minor bug but it risks a wrong interpretation of the results.

Thanks,
Gabriel.

**Comment by giaf** [comment]
hey!

test_param.h (and problem_size.h) are the leftovers of old code. I removed them now.

And, generally speaking, I should update the documentation :p
