### ISSUE TITLE
Length of "nu" in *_d_ip_ocp_hard_tv(), *_d_ip_ocp_hard_tv_work_space_size_bytes()

### ISSUE THREAD

**Issue by mkotlyar** [giaf/hpmpc#6]
The functions `*_d_ip_ocp_hard_tv()`, `*_d_ip_ocp_hard_tv_work_space_size_bytes()` expect their argument `nu` (size of control input) to point to an array of size `N+1` (`N`=number of control intervals). But `nu[N]` is always `0` (or are there cases when it can be non-0?).

Should it be changed so that `nu` points to an array of size `N` instead of `N+1`?

**Comment by giaf** [comment]
In the high-level API, now nu is an array of size N.

In the low-level API it is still expected to be of size N+1 with nu[N]==0 since this makes possible to handle the final stage as the previous ones.
