### ISSUE TITLE
Unsolved QP problem

### ISSUE THREAD

**Issue by mkotlyar** [giaf/hpmpc#8]
A problem that appears to be feasible could not be solved by HPMPC. The `c_order_d_ip_ocp_hard_tv()` makes 0 iterations and returns -1.

The code to reproduce the problem:
[test1.c.zip](https://github.com/giaf/hpmpc/files/329629/test1.c.zip)

Compile command:
```
 gcc test1.c -L. libhpmpc.a -lm -o test1 && ./test1
```

Output:
```
1.061400e+03	1.100000e+00	1.100000e+00	-nan	

Return code = -1
```

**Comment by mkotlyar** [comment]
It seems to be related to the fact that upper and lower bound for `x[0]` in this case are the same. If the bounds are relaxed the problem is solved.

Should HPMPC support cases when `lb == ub` or not?

**Comment by mkotlyar** [comment]
This test [test2.c.zip](https://github.com/giaf/hpmpc/files/329915/test2.c.zip) represents the same QP but without `lbx[0] == ubx[0] == x0`. The value of `b[0]` is replaced by as `b[0]+A[0]*x0`. The solver fails on it.

**Comment by giaf** [comment]
If nu[0]==1 and nx[0]==0, then has to be nb[0]<=1 (while in the test problem it is 3).

I think I will add checks for this kind of stuff in the high-level API.
